"""adding exercises

Revision ID: ece55b4f59f4
Revises: eda50a88992e
Create Date: 2022-10-07 01:40:37.034145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece55b4f59f4'
down_revision = 'eda50a88992e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lift_id', sa.Integer(), nullable=True),
    sa.Column('exercise_identifier', sa.String(length=32), nullable=True),
    sa.Column('srw_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lift_id'], ['lift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_exercise_identifier'), 'exercise', ['exercise_identifier'], unique=False)
    op.drop_column('lift', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lift', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_index(op.f('ix_exercise_exercise_identifier'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
